#!/bin/bash
REACT_APP_API_TYPE=backend
REACT_APP_API_BACKEND_ENDPOINT=<backend-url>
REACT_APP_AUDD_TOKEN=<your-audd-token>
REACT_APP_GENIUS_TOKEN=<your-genius-token>

export REACT_APP_API_TYPE REACT_APP_API_BACKEND_ENDPOINT REACT_APP_AUDD_TOKEN REACT_APP_GENIUS_TOKEN